### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by nightheronry** [dnkirill/stn_idsia_convnet#1]
Hi, how an awesome project. I am interested to learn more about the project. Could you send the dataset  used in the project to me ? thanks a lot.

**Comment by dnkirill** [comment]
Thanks! I used a slightly preprocessed (images are resized to 32x32 pixels and are pickled into train, validation and test subsets) GTSRB  dataset by Udacity: https://d17h27t6h515a5.cloudfront.net/topher/2016/November/581faac4_traffic-signs-data/traffic-signs-data.zip
